# This is a sample build configuration for Java – Gradle.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: uber/android-build-environment:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - (while sleep 3; do echo "y"; done) | android update sdk --filter "build-tools-25.0.2,android-25,extra-google-m2repository" --no-ui -a
          - ./gradlew assembleDebug
